### Site Settings ###
title               : MOGU Lab @ Wellesley
description         : >-
                      The Model-Guided Uncertainty (MOGU) Lab at Wellesley College is focused on developing new machine learning methods to help us better understand, predict and prevent suicide and related behaviors.
baseurl             : ""                                # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : mogu-lab/mogu-lab.github.io       # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                              # Opens external URLs in new tab (works for posts, projects and navbar only)
keywords            : Machine Learning, ML, Artificial Intelligence, AI, Mental Health, Suicide, Self-Injurious Thoughts and Behaviors, SITBs, Latent Variable Models, Bayesian Machine Learning, Generative Models, Research, Wellesley College, Computer Science

# Jekyll Sitemap 
url: "https://mogu-lab.github.io" 

# Jekyll WebP
webp:
  enabled: true
  
  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/img", "/assets/img/people"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files 
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  # Eg : "/usr/local/bin/cwebp"
  webp_path: nil

  # List of files or directories to exclude
  # e.g. custom or hand generated webp conversion files
  exclude: []

  # append '.webp' to filename after original extension rather than replacing it.
  # Default transforms `image.png` to `image.webp`, while changing to true transforms `image.png` to `image.png.webp`
  append_ext: false


### Plugins ###
jekyll-plugins:
  - jemoji
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-webp


### Navbar Settings ###
nav_exclude:                                       # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Yaniv Yacoby
#  image             : /assets/img/mogu-lab-logo.png
#  behance           : your_username
# dribbble          : your_username
#  email             : username@domain.com
#  facebook          : your_username
  github            : mogu-lab
# gitlab            : your_username
  instagram         : mogu.nuomi.paigu
# kaggle            : your_username
#  linkedin          : your_username
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /tutorials/:title


### Collections ###
collections:
  research:
    output: true
    permalink: /research/:name


### Disqus ###
#disqus:
#  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: G-H1X7VKL91W


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
      layout: "post"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"


### Jekyll Scholar ###
scholar:
  style: apa
  locale: en

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  # Note: if you have latex math in your bibtex, the latex filter
  # preprocessing may conflict with MathJAX if the latter is enabled.
  # See https://github.com/alshedivat/al-folio/issues/357.
  bibtex_filters: [latex, smallcaps, superscript]

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"


